Add pre-commit check for console.log...
Not disciplined enough to rely on the "nocommit" markers it seems

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -25,3 +25,13 @@ if [[ $rc != 1 ]]; then
   echo '(Use `git commit --no-verify` to skip commit hooks)';
   exit 1;
 fi
+
+git diff --cached | grep "^\+.*console\.log"
+rc=$?
+
+if [[ $rc != 1 ]]; then
+  echo ;
+  echo 'Trying to commit lines containing "console.log". Are you sure? (Aborting commit.)';
+  echo 'If you are sure, use `git commit --no-verify` to skip commit hooks';
+  exit 1;
+fi
